"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    appContainer: function (alertsExist) { return ({
        display: "flex",
        flexDirection: "row",
        height: alertsExist ? "calc(100% - 122px)" : "calc(100% - 72px)",
        width: "100%",
        pointerEvents: alertsExist ? "none" : "auto",
    }); },
    flex: {
        display: "flex",
    },
    appWrapper: {
        display: "flex",
        flexDirection: "column",
        height: "100%",
        width: "100%",
    },
    convosWrapper: {
        height: "100%",
        width: 320,
        position: "relative",
        backgroundColor: "#F4F4F6",
    },
    messagesWrapper: {
        flex: 1,
    },
    appHeader: {
        display: "flex",
        justifyContent: "space-between",
        backgroundColor: "#06033A",
        padding: "20px 25px",
    },
    appLogoWrapper: {
        width: "40px",
        height: "40px",
        borderRadius: "5px",
        border: "1.25px solid #394762",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    appLogoTitle: {
        fontSize: "14px",
        fontWeight: 600,
        textAlign: "center",
        color: "#FFFFFF",
        lineHeight: "20px",
        paddingLeft: "16px",
    },
    appLogoSubTitle: {
        fontSize: "12px",
        fontWeight: 600,
        textAlign: "left",
        color: "#AEB2C1",
        lineHeight: "20px",
    },
    userTile: {
        display: "flex",
        alignItems: "flex-start",
    },
    userName: {
        color: "#FFFFFF",
        fontSize: "12px",
        fontWeight: 600,
        lineHeight: "20px",
        display: "flex",
        justifyContent: "center",
    },
    userStatus: {
        fontSize: "12px",
        display: "flex",
        flexDirection: "row",
        lineHeight: "20px",
        fontWeight: "400",
        alignItems: "center",
        justifyContent: "center",
    },
    paginationSpinner: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: 16,
    },
    app: {
        flex: 1,
        height: "100%",
        width: "100%",
        position: "absolute",
    },
    buttonWrapper: {
        flexDirection: "row",
        paddingRight: "16px",
    },
    convosWrapperBox: {
        height: "100%",
        display: "flex",
        flexDirection: "column",
    },
    convoList: {
        overflowY: "auto",
        position: "absolute",
        top: "65px",
        bottom: "60px",
        width: "320px",
    },
    collapseButtonBox: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-end",
        width: "100%",
        paddingTop: "12px",
        paddingBottom: "20px",
        paddingRight: "16px",
        paddingLeft: "16px",
        position: "absolute",
        bottom: 0,
        borderTop: "1px solid #CACDD8",
    },
    newConvoButton: {
        padding: "14px 16px",
        width: "100%",
        borderBottom: "1px solid #CACDD8",
    },
    addParticipantsButton: {
        padding: "14px 16px",
        width: "100%",
    },
    loginContainer: {
        display: "flex",
        flexDirection: "column",
        height: "100%",
        backgroundColor: "#001489",
    },
    logo: {
        width: "42px",
    },
    loginTitle: {
        paddingTop: "2px",
        color: "#FFFFFF",
        fontSize: "20px",
        lineHeight: "28px",
        fontWeight: 500,
    },
    subTitle: {
        color: "#AEB2C1",
        fontSize: "14px",
        lineHeight: "20px",
        paddingBottom: "40px",
    },
    loginContent: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        position: "absolute",
        width: "100%",
        height: "100%",
        zIndex: 3,
    },
    loginForm: {
        backgroundColor: "#FFFFFF",
        borderRadius: "8px",
    },
    userInput: {
        paddingTop: "24px",
        width: "320px",
        marginLeft: "24px",
        marginRight: "24px",
    },
    passwordInput: {
        paddingTop: "16px",
        width: "320px",
        marginLeft: "24px",
        marginRight: "24px",
    },
    loginButton: {
        paddingTop: "32px",
        paddingBottom: "24px",
        marginLeft: "24px",
        marginRight: "24px",
    },
    loginBackground: {
        position: "absolute",
        alignSelf: "flex-end",
        top: "50%",
        height: "50%",
        width: "100%",
        backgroundColor: "#001489",
        overflow: "hidden",
    },
    modalInputLabel: {
        fontSize: "14px",
        fontWeight: 700,
        lineHeight: "20px",
    },
    settingsWrapper: {
        zIndex: 1,
        paddingTop: "22px",
    },
    optionWrapper: {
        width: "232px",
    },
    collapsedList: {
        width: "70px",
    },
};
